PetProject/Controllers/CartController.cs
using PetProject.Models.Abstract;
using PetProject.Models.Entities;
using PetProject.Models.NoSqlEntities;
using System;
using System.Linq;
using System.Web.Mvc;

namespace PetProject.Controllers
{
    public class CartController : BaseController
    {
        private IOrderProcessor orderProcessor;

        public CartController(IDBRepository repo, IOrderProcessor processor)
        {
            InjectedDBRepository = repo;
            orderProcessor = processor;
        }

        public ViewResult Index(Cart cart,string returnUrl)
        {
            FillCommonViewBag();

            return View(new CartIndexViewModel
            {
                Cart = cart,
                returnUrl = returnUrl
            });
        }

        public RedirectToRouteResult AddToCart(Cart cart, int PetId, string returnUrl)
        {
            FillCommonViewBag();

            Pet pet =null;

            try
            {
                pet = InjectedDBRepository.Pets.FirstOrDefault(g => g.PetId == PetId);
            }
            catch(Exception e)
            {
                logger.Error(e.Message);
            }

            if (pet != null)
            {
                cart.AddItem(pet, 1);
            }

            return RedirectToAction("Index", new { returnUrl });
        }

        public RedirectToRouteResult RemoveFromCart(Cart cart, int PetId, string returnUrl)
        {
            FillCommonViewBag();

            Pet pet = null;

            try
            {
                pet = InjectedDBRepository.Pets.FirstOrDefault(g => g.PetId == PetId);
            }
            catch(Exception e)
            {
                logger.Error(e.Message);
            }

            if (pet != null)
            {
                cart.RemoveLine(pet);
            }

            return RedirectToAction("Index", new { returnUrl });
        }

        public PartialViewResult Summary(Cart cart, bool small = false)
        {
            FillCommonViewBag();

            return PartialView(cart);
        }

        public ViewResult Checkout()
        {
            FillCommonViewBag();

            return View(new ShippingDetails());
        }

        [HttpPost]
        public ViewResult Checkout(Cart cart, ShippingDetails shippingDetails)
        {
            FillCommonViewBag();

            if (cart.Lines.Count() == 0)
            {
                ModelState.AddModelError("", "Sorry, the cart is empty!");
            }

            if (ModelState.IsValid)
            {
                orderProcessor.ProcessorOrder(cart, shippingDetails);
                cart.Clear();
                return View("Complete");
            }
            else
            {
                return View(shippingDetails);
            }
        }

        public ViewResult Complete()
        {
            FillCommonViewBag();

            return View();
        }
    }
}

PetProject/Controllers/DetailController.cs
using PetProject.Models.Repository;
using PetProject.Models.Entities;
using System;
using System.Collections.Generic;
using System.IO;
using System.Web;
using System.Web.Mvc;
using PetProject.Models.Abstract;
using PetProject.Models.NoSqlEntities;

namespace PetProject.Controllers
{
    public class DetailController : BaseController
    {
        public DetailController(IDBRepository repo)
        {
            InjectedDBRepository = repo;
        }

        // GET: Detail
        public ActionResult Index(int? oid)
        {
            FillCommonViewBag();

            List<Pet> listPet = new List<Pet>();

            try
            {
                if (oid == null || oid == 0)
                {
                    throw new Exception();
                }

                listPet = InjectedDBRepository.GetAllPetsByOwnerId((int)oid);
                ViewBag.OwnerId = (int)oid;
                ViewBag.OwnerName = InjectedDBRepository.FindOwner((int)oid).Name;
            }
            catch(Exception e)
            {
                logger.Error(e.Message);
                return RedirectToAction("Index", "Home", new { notify = PrepareWarningMessageBox() });
            }

                return View(listPet);
        }

        public ActionResult PetSummary(int? pid, string returnUrl)
        {
            FillCommonViewBag();

            ViewBag.ReturnUrl = returnUrl;

            Pet pet = null;

            try
            {
                if (pid == null || returnUrl == null)
                {
                    throw new Exception();
                }

                pet = InjectedDBRepository.FindPet(pid ?? 0);

                if (pet == null)
                {
                    throw new Exception();
                }
            }

            catch(Exception e)
            {
                logger.Error(e.Message);
                return RedirectToAction("Index", "Home", new { notify = PrepareWarningMessageBox() });
            }

            return View(pet);
        }

        #region <Create>

        [HttpGet]
        public ActionResult Create(int? oid)
        {
            try
            {
                if (oid == null || oid == 0)
                {
                    throw new Exception();
                }
                else
                {
                    if (InjectedDBRepository.FindOwner(oid ?? 0) == null)
                    {
                        throw new Exception();
                    }
                }
            }
            catch (Exception e)
            {
                logger.Error(e.Message);
                return RedirectToAction("Index", "Home", new { notify = PrepareWarningMessageBox() });

            }

            Pet pet = new Pet();

            pet.OwnerId = (int)oid;

            return PartialView(pet);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Pet pet)
        {
            try
            {
                pet.Name = Utils.DeleteSpecialCharacters(pet.Name);
                try { pet.LastEditedBy = HttpContext.User.Identity.Name; } catch { pet.LastEditedBy = "UnitTests"; }
                pet.LastEditedAt = DateTime.UtcNow;

                if (ModelState.IsValid)
                {
                    try
                    {
                        using (var db = new DB())
                        {
                            string petImagePath = SavePetImageFile();

                            if (!string.IsNullOrEmpty(petImagePath))
                            {
                                pet.ImagePath = petImagePath;
                            }

                            db.InjectedContext.PetsDoAdd(pet);
                            db.InjectedContext.SaveChanges();
                        }

                        string msg = string.Format(@"{0} has been created.", pet.Name);
                        logger.Info(msg);
                        TempData["message"] = msg;
                        return RedirectToAction("Index", "Detail", new { oid = pet.OwnerId });
                    }
                    catch (Exception e)
                    {
                        throw new Exception();
                    }
                }
                else
                {
                    throw new Exception();
                }
            }
            catch(Exception e)
            {
                logger.Error(e.Message);
                return RedirectToAction("Index", "Detail", new { notify = PrepareWarningMessageBox() });
            }
        }
        #endregion

        #region <Edit>

        public ActionResult Edit(int? pid)
        {
            Pet pet = null;

            try
            {
                if (pid != null)
                {
                    pet = InjectedDBRepository.FindPet(pid ?? 0);
                }

                if (pet == null)
                {
                    throw new Exception();
                }

                try
                {
                    UpdateModel(pet, new FormValueProvider(ControllerContext));
                }
                catch { }
            }
            catch(Exception e)
            {
                logger.Error(e.Message);
                return RedirectToAction("Index", "Home", new { notify = PrepareWarningMessageBox() });
            }

            return PartialView(pet);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Pet pet)
        {
            try
            {
                pet.Name = Utils.DeleteSpecialCharacters(pet.Name);
                try { pet.LastEditedBy = HttpContext.User.Identity.Name; } catch { pet.LastEditedBy = "UnitTests"; }
                pet.LastEditedAt = DateTime.UtcNow;

                if (ModelState.IsValid)
                {
                    using (var db = new DB())
                    {
                        var existPet = db.InjectedContext.FindPet(pet.PetId);
                        if (existPet != null)
                        {
                            existPet.Name = pet.Name;
                            existPet.ImagePath = EditPetImageFile(existPet.ImagePath, pet.ImagePath);
                            existPet.LastEditedBy = pet.LastEditedBy;
                            existPet.LastEditedAt = pet.LastEditedAt;

                            db.InjectedContext.SaveChanges();
                        }
                    }

                    string msg = string.Format(@"{0} has been edited.", pet.Name);
                    logger.Info(msg);
                    TempData["message"] = msg;
                    return RedirectToAction("Index", "Detail", new { oid = pet.OwnerId });
                }
                else
                {
                    throw new Exception();
                }
            }
            catch (Exception e)
            {
                logger.Error(e.Message);
                return RedirectToAction("Index", "Home", new { notify = PrepareWarningMessageBox() });
            }
        }

        #endregion

        #region Delete

        [HttpGet]
        public ActionResult Delete(int? pid)
        {
            Pet pet = new Pet();

            try
            {
                if (pid == null || pid == 0)
                {
                    throw new Exception();
                }

                pet = InjectedDBRepository.FindPet(pid ?? 0);


                if (pet == null)
                {
                    throw new Exception();
                }

                try
                {
                    UpdateModel(pet, new FormValueProvider(ControllerContext));
                }
                catch { }
            }
            catch(Exception e)
            {
                logger.Error(e.Message);
                return RedirectToAction("Index", "Detail", new { notify = PrepareWarningMessageBox() });
            }

            return PartialView(pet);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(Pet pet, Cart cart)
        {
            try
            {
                string petName = pet.Name;

                using (var db = new DB())
                {
                    try
                    {
                        cart.RemoveLine(pet);
                    }
                    catch { }

                    try
                    {
                        if (!string.IsNullOrEmpty(pet.ImagePath))
                        {
                            DeletePetImageFile(pet.ImagePath);
                        }
                    }
                    catch { }

                    db.InjectedContext.PetsDoRemove(pet);
                    db.InjectedContext.SaveChanges();
                }

                string msg = string.Format(@"{0} has been deleted.", petName);
                logger.Info(msg);
                TempData["message"] = msg;
                return RedirectToAction("Index", "Detail", new { oid = pet.OwnerId });
            }
            catch (Exception e)
            {
                logger.Error(e.Message);
                return RedirectToAction("Index", "Detail", new { notify = PrepareWarningMessageBox() });
            }
        }

        #endregion

        #region UtilsWorkWithPetImageFile

        private string SavePetImageFile(string autoFileName = null)
        {
            HttpPostedFileBase myFile = HttpContext.Request.Files["ImagePath"];
            string targetLocation = Server.MapPath("~/Content/PetImages");
            if (autoFileName == null)
            {
                autoFileName = DateTime.UtcNow.Ticks.ToString();
            }

            string resultFileName = null;

            if (myFile != null)
            {
                if (myFile.ContentLength == 0) return null;

                FileInfo fi = new FileInfo(myFile.FileName);
                string ext = fi.Extension.ToLower();

PetProject/Controllers/NavController.cs
using PetProject.Models.Abstract;
using PetProject.Models.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PetProject.Controllers
{
    public class NavController : BaseController
    {
        public NavController(IDBRepository repo)
        {
            InjectedDBRepository = repo;
        }

        [ChildActionOnly]
        public PartialViewResult OwnerMenu(int? oid = null)
        {
            ViewBag.SelectedOnwerId = oid ?? -1;

            List<Owner> owners = new List<Owner>();

            try
            {
                owners = InjectedDBRepository.Owners.OrderBy(x => x.Name).ToList();
            }
            catch(Exception e)
            {
                logger.Error(e.Message);
            }

            return PartialView(owners);
        }
    }
}

PetProject/Views/Detail/Create.cshtml
@model PetProject.Models.Entities.Pet

<link rel="stylesheet" type="text/css" href="~/Content/CustomFileInput.css" />
<script src="~/Scripts/ModalNotification/ValidationMessages.js" type="text/javascript"></script>
<script src="~/Scripts/ModalNotification/PetValidation.js" type="text/javascript"></script>
<script src="~/Scripts/ModalNotification/UplaodImageValidation.js" type="text/javascript"></script>

<div class="usermodalwindow">
    <div class="modal-header">
        <h3 class="modal-title" id="myModalLabel" style="color: green;">
            Creating a pet
        </h3>
    </div>

    @using (Html.BeginForm("Create", "Detail", FormMethod.Post, new { @enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)

        <div class="modal-body">
            <fieldset>
                <label>Name:</label>
                <div class="editor-field">
                    @Html.TextBoxFor(model => model.Name, new { @class = "form-control", @autocomplete = "off" })
                    @Html.ValidationMessageFor(model => model.Name)
                </div>

                <label>Photo:</label>
                <div class="editor-field">
                    <ul class="list-inline">
                        <li>
                            <span class="btn btn-info fileinput-button">
                                <i class="glyphicon glyphicon-plus"></i>
                                <span>Upload</span>
                                <input type="file" max-size="65535" name="ImagePath" class="form-control" />
                            </span>
                        </li>
                        <li><label id="fileNameErrorMessage" class="error"></label></li>
                    </ul>
                </div>

                @Html.HiddenFor(model => model.OwnerId)
                @Html.HiddenFor(model => model.PriceExhibition)
                @Html.HiddenFor(model => model.LastEditedBy)
                @Html.HiddenFor(model => model.LastEditedAt)
</fieldset>
        </div>

        <div class="modal-footer">
            <a href="/Detail/Index?oid=@Model.OwnerId" class="btn btn-default">
                Cancel
            </a>
            <input type="submit" class="btn btn-success" value="Save" />
        </div>
    }
</div>

PetProject/Views/Detail/Delete.cshtml
@model PetProject.Models.Entities.Pet

<div class="usermodalwindow">
    <div class="modal-header">
        <h3 class="modal-title" id="myModalLabel" style="color: red;">
            Deleting the pet
        </h3>
    </div>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.PetId)
        @Html.HiddenFor(model => model.Name)
        @Html.HiddenFor(model => model.OwnerId)
        @Html.HiddenFor(model => model.ImagePath)
        @Html.HiddenFor(model => model.PriceExhibition)

        <div class="modal-body">
            <fieldset>
                <div class="display-label">
                    @Html.DisplayFor(model => model.Name)
                </div>
            </fieldset>
        </div>

        <div class="modal-footer">
            <a href="/Detail/Index?oid=@Model.OwnerId" class="btn btn-default">
                Cancel
            </a>
            <input type="submit" class="btn btn-danger" value="Delete" />
        </div>
    }
    </div>

PetProject/Views/Detail/Edit.cshtml
@model PetProject.Models.Entities.Pet

<link rel="stylesheet" type="text/css" href="~/Content/CustomFileInput.css" />
<script src="~/Scripts/ModalNotification/ValidationMessages.js" type="text/javascript"></script>
<script src="~/Scripts/ModalNotification/PetValidation.js" type="text/javascript"></script>
<script src="~/Scripts/ModalNotification/UplaodImageValidation.js" type="text/javascript"></script>

<div class="usermodalwindow">
    <div class="modal-header">
        <h3 class="modal-title" id="myModalLabel" style="color: green;">
            Editing the pet
        </h3>
    </div>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)

        <div class="modal-body">
            <fieldset>
                <label>Имя:</label>
                <div class="editor-field">
                    @Html.TextBoxFor(model => model.Name, new { @class = "form-control", @autocomplete = "off" })
                    @Html.ValidationMessageFor(model => model.Name)
                </div>

                <label>Фото:</label>
                <div class="editor-field">
                    <ul class="list-inline">
                        <li>
                            <span class="btn btn-info fileinput-button">
                                <i class="glyphicon glyphicon-plus"></i>
                                <span>Upload</span>
                                <input type="file" max-size="65535" name="ImagePath" class="form-control" />
                            </span>
                        </li>
                        <li><label id="fileNameErrorMessage" class="error"></label></li>
                    </ul>
                </div>

                @Html.HiddenFor(model => model.PetId)
                @Html.HiddenFor(model => model.OwnerId)
                @Html.HiddenFor(model => model.PriceExhibition)
                @Html.HiddenFor(model => model.LastEditedBy)
                @Html.HiddenFor(model => model.LastEditedAt)
            </fieldset>
        </div>

        <div class="modal-footer">
            <a href="/Detail/Index?oid=@Model.OwnerId" class="btn btn-default">
                Close
            </a>
            <input type="submit" class="btn btn-success" value="Save" />
        </div>
    }
</div>

PetProject/Views/Detail/Index.cshtml
@model IEnumerable<PetProject.Models.Entities.Pet> 

@{
    ViewBag.Title = ViewBag.OwnerName + "`s pets";
}

<div class="visible-xs">
    @Html.Action("Summary", "Cart", new { small = true })
</div>
<div class="hidden-xs">
    @Html.Action("Summary", "Cart", new { small = false })
</div>

<h1>@ViewBag.OwnerName<span>`s pets</span></h1>

<p style="margin: 0 0 10px">
    <a href="/Home/Index">Back to All Users</a>
</p>

<div class="row panel">
    <div id="ownerMenu" class="hidden-xs col-sm-3">
        @Html.Action("OwnerMenu", "Nav")
    </div>
    <div class="col-xs-12 col-sm-9">
        <p style="margin: 0 0 10px">
            <button data-toggle="modal" data-target="#myModal" href="/Detail/Create?oid=@ViewBag.OwnerId" class="btn btn-success" title="Add">Add</button>
        </p>

        <table class="table table-striped table-bordered table-hover">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Name)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.ImagePath)
                    </th>
                    <th>
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
            {
                    <tr>
                        <td>
                            @Html.DisplayFor(p => item.Name)
                        </td>
                        <td>
                            <img class="img-responsive" src="@item.ImagePath" runat="server" alt="" />
                        </td>
                        <td>
                            <button data-toggle="modal" data-target="#myModal" href="/Detail/Edit?pid=@item.PetId"
                                    class="btn btn-primary glyphicon glyphicon-pencil" title="Edit"></button>
                            <button data-toggle="modal" data-target="#myModal" href="/Detail/Delete?pid=@item.PetId"
                                    class="btn btn-primary glyphicon glyphicon-trash" title="Delete"></button>
                            <button data-toggle="modal" data-target="#myModal"  href="/Detail/PetSummary?pid=@item.PetId&returnUrl=@Request.Url.PathAndQuery"
                                    class="btn btn-primary glyphicon glyphicon-shopping-cart" title="Cart"></button>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

    <!-- Modal-->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
            </div>
        </div>
    </div>

PetProject/Views/Detail/PetSummary.cshtml
@model PetProject.Models.Entities.Pet

<div class="usermodalwindow">
    <div class="modal-header">
        <h3 class="modal-title" id="myModalLabel" style="color: green;">
            Adding the Pet to Favorites
        </h3>
    </div>

    @using (Html.BeginForm("AddToCart", "Cart"))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)

        <div class="modal-body">
            <fieldset>
                <div class="display-label">
                    @Html.DisplayFor(model => model.Name)
                </div>

                @Html.HiddenFor(model => model.PetId)
                @Html.Hidden("returnUrl", (string)ViewBag.ReturnUrl)
            </fieldset>
        </div>

        <div class="modal-footer">
            <a href="/Detail/Index?oid=@Model.OwnerId" class="btn btn-default">
                Close
            </a>
            <input type="submit" class="btn btn-success" value="Add" />
        </div>
    }
</div>